### ISSUE TITLE
gdb segmentation fault

### ISSUE THREAD

**Issue by anassmeskini** [pinam45/dynamic_bitset#2]
When debugging code that uses ``dynamic_bitset`` with ``gdb`` I get a segmentation fault when I try to print a bitset.
```
(gdb) print bitset[0]
$1 = {m_block = @0xd, m_mask = 93825020145982}
(gdb) print bitset
$2 = {Segmentation fault 
```
Also, how should I read the output of the first print?

**Comment by pinam45** [comment]
For
```
(gdb) print bitset
```
no code from the bitset is called, gdb just print the "raw" content of the ``bitset`` object (public and private fields). I think the memory of your program is corrupted, so gdb fail to print the object content, most of the time it is because you have an undefined behaviour in your code.
Do you have a minimal working example for me to test it?

For
```
(gdb) print bitset[0]
```
the ``operator[]`` of the dynamic bitset return a proxy class for non-const bitsets (so you can do ``bitset[0] = true``) that have an implicit bool cast operator. gdb show you the content of the proxy class, ``m_block`` is a reference to the block of the bitset that contain the bit you want and ``m_mask`` is the mask to apply on the block to get the bit you want.

If you want to know the value of a bit, if I remember well, with recent gdb version you can cast the result to bool and it will call the cast operator of the proxy class and give you the bit value. Or you can use the ``test`` method:
```
(gdb) print bitset.test(0)
$1 = true
```

**Comment by anassmeskini** [comment]
I checked with valgrind and sanitizers and they can't find any memory related problems.
Also, I am not sure if it's normal for a memory problem in my code to cause gdb to segfault.
When I commented the code in ``dynamic_bitset.hpp`` and added
`
template <int = 0>
using dynamic_bitset = std::vector<bool>
`
it worked fine.

It's clear that your code is not responsible for the segfault, so I am not sure how to explain it.
