### ISSUE TITLE
Binary (assignment) operations should not require the same `size()`

### ISSUE THREAD

**Issue by a-ludi** [pinam45/dynamic_bitset#4]
Binary (assignment) operations require the same `size()` of their operands ([example](https://github.com/pinam45/dynamic_bitset/blob/968b396cd2a7cfd2654d074242aed6d23ded2591/include/sul/dynamic_bitset.hpp#L2058)). While this makes the implementation easy it enforces additional boilerplate code if the user wants to use differently-sized sets.

The implementation will still be easy as the resulting bit set will either have the smaller or the larger of both `size()`s:

In case of assignment operators I would expect the LHS operand to expand its `size()` to fit the RHS if required. Of course, the loops must only iterate to the minimum of both sizes.

In case of binary operators it should be sufficient to swap LHS and RHS in order to avoid additional reallocations.

**Comment by pinam45** [comment]
Thank you for your issue, operator behaviors is a difficult topic for dynamic bitsets because the operators must be consistants with each others. For example if I implement your proposition on **operator&=** I must also change **operator&** because:
```cpp
sul::dynamic_bitset<> a(4, 0b1010);
sul::dynamic_bitset<> b(2, 0b10);
a &= b;
return a;
```
must be equivalent to:
```cpp
sul::dynamic_bitset<> a(4, 0b1010);
sul::dynamic_bitset<> b(2, 0b10);
a = a & b;
return a;
```
(in therm of value, not code complexity or memory allocations)

The example was quite obvious, but for your proposition it correspond in fact as treating the bitset as a number instead of a container whith the classical number representation "if there is no digit on the left act as if it was 0, so 1010 & 10 = 0010". The **sul::dynamic_bitset** is designed to be first a container *(sadly not in the holy standard sense because dynamic bitsets can't provide iterators because of the reference proxy class used to access the bits)*, for example:
```cpp
sul::dynamic_bitset<> a(3, 0b010);
sul::dynamic_bitset<> b(2, 0b10);
return a != b;
```
return **true**, because the two bitsets are different even if taken as numbers 010 is the same as 10. This have implications on the others operators, the biggest being the comparisons operators all based on "<" which must also compare the size, there is a complete explanation of why in [the documentation of the operator<](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#ae2f4a40605ad4ca4dd8a6ba14113857a).

So I am not really sure of the involvement on the properties of the operator if I interpret the bitsets as a number. Another solution is to keep the current behaviour of the operator and add a function like "padded_and" or "numerical_and".

Also it seems that other dynamic bitsets implementations like **boost** ([here](https://github.com/boostorg/dynamic_bitset/blob/b59fc97a670a1cd1866ea4a46612525a17752978/include/boost/dynamic_bitset/dynamic_bitset.hpp#L863)) made the same choice.

**Comment by pinam45** [comment]
Ok found a property that will be broken if operators works like on numbers by adding left *0* on the shorter bitset. Lets take the xor (operator^), one of his properties is that it is his "self-inverse", meaning **(a ^ b ^ b) == a** is true.
With the "number-like" modification:
```cpp
sul::dynamic_bitset<> a(2, 0b10);
sul::dynamic_bitset<> b(4, 0b1010);
assert( (a ^ b ^ b) == a ); // false
```
with steps:
```cpp
sul::dynamic_bitset<> a(2, 0b10);
sul::dynamic_bitset<> b(4, 0b1010);
sul::dynamic_bitset<> c(a); // c is 10
c ^= b: // c is 1000
c ^= b: // c is 0010
assert( c == a ); // false
```
so I won't implement the behavior but maybe add "number-like operator" functions, or course with a number-like comparison function because all this operators properties problems come from the requirements of the holy standard on the *operator==* of container.

**Comment by a-ludi** [comment]
That's true although I was aiming for a set-theoretic implementation rather than number-like. That means two sets `A` and `B` are equal if and only if for all `a in A` holds `a in B` and vice versa for all `b in B` holds `b in A`.

In contrast, your implementation has the functionality of a bit vector. Of course, any two vectors that have different length are different by definition. Also the behavior of  binary operators between different-length vectors is undefined.

I was not aware of the difference when I posted the issue. So thanks for your comments but please keep your implementation as clean as it is.

One more note. Adding more methods to `dynamic_bitset` will clutter its namespace and still fails to provide a sound set-theoretic implementation. I would think it best to implement it as either a subclass or friend-class using the underlying bit vector.

**Comment by a-ludi** [comment]
In fact, the set-theoretic implementation should be a friend class of `dynamic_bitset` rather than a subclass because the `is_a` relation does not hold, e.i. a set-theoretic bit set is *not* a bit vector.

**Comment by pinam45** [comment]
Very interesting, in fact my biggest use of the *sul::dynamic_bitset* was for representing sets in my research project [USCP](https://github.com/pinam45/USCP), but for this project advanced set-specific features were not necessary and all sets were the same size so I just used my dynamic_bitset without thinking about it too much.

As you wrote my implementation is more a bit vector, and it seems that most dynamic bitsets implementation are like this, trying to be a *std::bitset* with the features of *std::vector*. I didn't find a good set-theoretic implementation online, it could be interesting to do one using *sul::dynamic_bitset*.

Or maybe a set-theoretic implementation of a bitset alone is not common but there is multiple implementations available that are part of bigger set theory libraries where you define first a universe with all your elements and then sets that use bitsets to indicate for each element if it is part of the set. Not sure though, I never used a set theory library, but I will check this next time I work with sets.
