### ISSUE TITLE
Missing .data() for binary serialization

### ISSUE THREAD

**Issue by soufianekhiat** [pinam45/dynamic_bitset#5]
Very cool,

I'm using it on my side with minor modification:
```
constexpr std::byte* data()
{
	return reinterpret_cast<std::byte*>(&m_blocks[0]);
}
constexpr std::byte const* data() const
{
	return reinterpret_cast<std::byte const*>(&m_blocks[0]);
}
```
Which is on my side convenient for binary serialization.

**Comment by pinam45** [comment]
Oh I missed the notification!

Thank you for the comment, `std::vector` has a `data()` function, could be a good idea to add one to the `dynamic_bitset`.
`std::vector` ensure that `[data(); data() + size())` is always a valid range which won't be true for a `dynamic_bitset` because `size()` return the number of bits but I don't think it will be too misleading for the users if I make sure to specify the valid range in the documentation.

**Comment by pinam45** [comment]
Took me some time because of various unrelated events, and CI problems with Github Actions removing set-env (see de9c11439fe2de374683e61e17bc1633fa5e9132), but [v1.2.0](https://github.com/pinam45/dynamic_bitset/releases/tag/v1.2.0) added the ``.data()`` functions:
   - [constexpr typename dynamic_bitset<Block, Allocator>::block_type* dynamic_bitset<Block, Allocator>::data() noexcept](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#ad67d6b126707fecda32e4f363dc08394)
   - [constexpr const typename dynamic_bitset<Block, Allocator>::block_type* dynamic_bitset<Block, Allocator>::data() const noexcept](https://pinam45.github.io/dynamic_bitset/classsul_1_1dynamic__bitset.html#adfe46260b7caff45a27990b37b771a98)
